baseURL: "https://ranjithkumar.netlify.app/"
languageCode: "en-us"
title: "my page"
theme: hugo-profile

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  title: "Personal Portfolio"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # Hero
  hero:
    enable: true
    Intro: "Hi, my name is"
    title: " RANJITHKUMAR V "
    # subtitle: "I build things for the web"
    content: "I am an Engineering Graduate in Information Technology.
              Bachelor of Technology in Bannari Amman Institute Of Technology.
              I have a CGPA of 8.39.
              My father's name is Varadharaj P.
              My mother's name is Malarani V.
              "
             
    image: /IMG-20220324-WA0034.jpg
    button:
      enable: true
      name: "Resume"
      url: "/Ranjithkumar_resume.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://example.com
        - icon: fab fa-twitter
          url: https://example.com
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/IMG-20220324-WA0034.jpg"
    content: |-
      I am an Engineering Graduate. 
      department: Information Technology.
      cgpa: 8.39.
      
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Java"
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "Bootstrap"
        - "React JS"
        - "MYSQL"
  
  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Bannari Amman Institute Of Technology, B-tech, Sathyamangalam"
        school: 
          name: "Bannari Amman Institute Of Technology"
          url: "https://www.google.com/search?gs_ssp=eJzj4tTP1TdIqrIoKDNg9OJNSszLSyzKVEjMzU3MAwBtNAiW&q=bannari+amman&rlz=1C1SQJL_enIN942IN942&oq=bannari+amma&aqs=chrome.1.69i57j46i39j46i20i175i199i263i512j0i67j46i199i465i512j46i131i175i199i433i512j0i512j69i61.8946j0j4&sourceid=chrome&ie=UTF-8"
        year of passing: "2019 - 2023"
        CGPA: "8.39"
      - title: "SRM Muthamizhl Higher Secondary School, Periyeri"
        school:
          name: "SRM Muthamizhl Higher Secondary School, Periyeri"
          url: "https://targetstudy.com/school/69600/muthamizhi-higher-secondary-school/"
        
        content: |-
        featuredLink:
          enable: true
          name: ""
  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: rk0730157@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/ranjithkumar-it19
      linkedin: https://www.linkedin.com/in/ranjithkumar-v-0a85611aa/

